<a href="https://colab.research.google.com/github/AmanSingh0909/Data-engineer-learning-from-linkedin/blob/main/Data_Cleaning_using_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

df = pd.read_csv('/content/Student_Performance_Dataset.csv')

In [ ]:
drop_df = df.dropna()
print(drop_df.to_string())

     Student_ID  Age  Gender  Class  Study_Hours_Per_Day  Attendance_Percentage Parental_Education Internet_Access Extracurricular_Activities  Math_Score  Science_Score  English_Score  Previous_Year_Score  Final_Percentage Performance_Level Pass_Fail
0         S0001   15    Male     12                  1.0                     65       Postgraduate              No                         No          40             39             72                   81             50.33           Average      Pass
1         S0002   19  Female      9                  1.6                     58           Graduate              No                        Yes          80             44             35                   47             53.00           Average      Pass
2         S0003   14  Female     12                  3.6                     64        High School             Yes                        Yes          83             73             59                   58             71.67              Good      Pass
3         S0004   18  Female      9                  5.5                     68       Postgraduate             Yes                         No          68             48             77                   54             64.33           Average      Pass
4         S0005   14    Male     10                  5.0                     80        High School             Yes                         No          41             46             36                   68             41.00              Poor      Fail
5         S0006   19    Male     12                  5.2                     82        High School              No                        Yes          88             70             46                   60             68.00              Good      Pass
6         S0007   16    Male     12                  0.8                     78        High School              No                         No          75             69             64                   84             69.33              Good      Pass
7         S0008   18  Female     11                  2.0                     81           Graduate              No                        Yes          93             37             48                   55             59.33           Average      Pass
8         S0009   18  Female     11                  3.5                     61           Graduate              No                         No          55             39             83                   71             59.00           Average      Pass
9         S0010   18    Male     10                  5.7                     97        High School             Yes                         No          72             73             73                   61             72.67              Good      Pass
10        S0011   14  Female      9                  3.6                     88           Graduate             Yes                         No          95             85             69                   41             83.00         Excellent      Pass
11        S0012   18  Female      9                  5.7                     74       Postgraduate             Yes                         No          54             38             59                   81             50.33           Average      Pass
12        S0013   19    Male     10                  1.5                     64       Postgraduate             Yes                        Yes          35             95             37                   85             55.67           Average      Pass
13        S0014   17  Female     10                  5.5                     76       Postgraduate              No                        Yes          79             82            100                   71             87.00         Excellent      Pass
14        S0015   15  Female     10                  4.2                     60       Postgraduate              No                        Yes          55             57             80                   72             64.00           Average      Pass
15        S0016   17    Male     12                  5.0                     67       Postgraduate              No                         No          68             40             81                   72             63.00           Average      Pass
16        S0017   16    Male     10                  4.0                     66           Graduate              No                        Yes          49             59             96                   63             68.00              Good      Pass
17        S0018   14  Female      9                  5.0                     89        High School              No                        Yes          71             40             59                   82             56.67           Average      Pass
18        S0019   14  Female     12                  1.9                    100       Postgraduate              No                         No          45             85             74                   61             68.00              Good      Pass
19        S0020   19    Male     11                  3.6                     66        High School             Yes                        Yes          75             78             59                   78             70.67              Good      Pass
20        S0021   15  Female     10                  4.7                     65        High School              No                        Yes          46             80             70                   46             65.33           Average      Pass
21        S0022   15    Male     12                  2.8                     83       Postgraduate              No                        Yes         100             96             99                   86             98.33         Excellent      Pass
22        S0023   19  Female     12                  5.3                     72       Postgraduate              No                         No          72             40             63                   76             58.33           Average      Pass
23        S0024   14  Female     10                  4.6                     54        High School             Yes                         No          58             37             79                   94             58.00           Average      Pass
24        S0025   17    Male     10                  0.9                     98       Postgraduate             Yes                         No          61             53             38                   48             50.67           Average      Pass
25        S0026   19  Female      9                  5.1                     78           Graduate              No                         No          68             80             69                   43             72.33              Good      Pass
26        S0027   19  Female     12                  2.0                     75        High School              No                         No          56             79             52                   94             62.33           Average      Pass
27        S0028   14    Male     12                  0.9                     91           Graduate              No                        Yes          57             51             35                   52             47.67              Poor      Fail
28        S0029   19  Female     12                  4.3                     87           Graduate              No                         No          61             91             49                   49             67.00              Good      Pass
29        S0030   16  Female     11                  3.5                     69           Graduate             Yes                        Yes          81             68             42                   57             63.67           Average      Pass
30        S0031   18  Female      9                  1.8                     85           Graduate             Yes                        Yes          64             58             93                   93             71.67              Good      Pass
31        S0032   17    Male     12                  1.1                     78        High School              No                         No          47             81             87                   52             71.67              Good      Pass
32        S0033   17    Male     10                  1.4                     58        High School              No                        Yes          54             49             75                   66             59.33           Average      Pass
33        S0034   17  Female     11                  3.0                     94           Graduate              No                         No          56             51             45                   61             50.67           Average      Pass
34        S0035   15  Female     12                  2.3                     79           Graduate              No                        Yes          97             95             53                   93             81.67         Excellent      Pass
35        S0036   18  Female     10                  3.4                     87        High School              No                         No          95             86             35                   68             72.00              Good      Pass
36        S0037   18  Female     10                  3.9                     54           Graduate              No                        Yes          82            100             71                   50             84.33         Excellent      Pass
37        S0038   18    Male     11                  1.2                     63        High School             Yes                        Yes          65             56             73                   89             64.67           Average      Pass
38        S0039   16    Male     11                  1.7                     97       Postgraduate             Yes                        Yes          75             64             94                   94             77.67              Good      Pass
39        S0040   17    Male     12                  2.0                    100           Graduate             Yes                        Yes          68             38             88                   59             64.67           Average      Pass
40        S0041   16    Male     10                  5.2                     95           Graduate             Yes                         No          56             84             57                   57             65.67           Average      Pass
41        S0042   19  Female     11                  4.1                     64        High School              No                        Yes          62             82             95                   78             79.67              Good      Pass
42        S0043   18    Male     12                  4.5                     56        High School             Yes                        Yes          60             70             52                   86             60.67           Average      Pass
43        S0044   16  Female      9                  4.8                     68        High School             Yes                        Yes          37             76             98                   44             70.33              Good      Pass
44        S0045   14  Female     10                  3.4                     91           Graduate              No                         No          36            100             76                   62             70.67              Good      Pass
45        S0046   14    Male      9                  1.9                     55        High School              No                         No          87             37             55                   46             59.67           Average      Pass
46        S0047   14    Male     10                  2.6                     96           Graduate             Yes                         No          68             63             78                   43             69.67              Good      Pass
47        S0048   19    Male     12                  0.8                     80           Graduate             Yes                        Yes          46             49             92                   83             62.33           Average      Pass
48        S0049   17    Male     12                  1.0                     63        High School              No                         No          41             86             46                   58             57.67           Average      Pass
49        S0050   14  Female     11                  2.8                     95        High School              No                         No          44             83             83                   93             70.00              Good      Pass
50        S0051   18    Male     11                  1.3                     69        High School              No                         No          99             77             84                   88             86.67         Excellent      Pass
51        S0052   18  Female     11                  5.3                     63           Graduate             Yes                        Yes          82             63             72                   55             72.33              Good      Pass
52        S0053   15    Male     11                  4.7                     76        High School             Yes                         No          82             87             42                   89             70.33              Good      Pass
53        S0054   17  Female     11                  1.5                     92        High School             Yes                         No          57             75             86                   81             72.67              Good      Pass
54        S0055   17  Female     11                  5.3                     80           Graduate              No                         No          74             37             46                   40             52.33           Average      Pass
55        S0056   15  Female     12                  4.2                     75           Graduate             Yes                         No          86             71             79                   58             78.67              Good      Pass
56        S0057   16  Female     12                  3.9                     97           Graduate             Yes                         No          81             72             85                   40             79.33              Good      Pass
57        S0058   19    Male      9                  3.0                     64       Postgraduate              No                        Yes          66             57             69                   86             64.00           Average      Pass
58        S0059   14    Male     12                  3.6                     90           Graduate              No                        Yes          67             82            100                   86             83.00         Excellent      Pass
59        S0060   17  Female     10                  3.5                     51       Postgraduate             Yes                        Yes          68             74             81                   68             74.33              Good      Pass
60        S0061   14    Male      9                  4.0                     82       Postgraduate              No                        Yes          65             83             53                   95             67.00              Good      Pass
61        S0062   17  Female     10                  1.8                     99       Postgraduate              No                         No          78             35             91                   65             68.00              Good      Pass
62        S0063   19  Female     11                  1.9                     66        High School              No                         No          95             82             89                   52             88.67         Excellent      Pass
63        S0064   19  Female     12                  1.9                     56           Graduate             Yes                         No          75             40             40                   86             51.67           Average      Pass
64        S0065   19    Male     12                  3.6                     84           Graduate             Yes                         No          85             71             53                   95             69.67              Good      Pass
65        S0066   14  Female     10                  2.7                     55        High School             Yes                         No          67             60             84                   65             70.33              Good      Pass
66        S0067   14  Female     10                  4.4                     71       Postgraduate             Yes                         No          64             47             66                   54             59.00           Average      Pass
67        S0068   17    Male     10                  5.4                     96       Postgraduate              No                        Yes          43             86             65                   81             64.67           Average      Pass
68        S0069   17    Male     10                  3.4                     77        High School              No                         No          35             77             97                   83             69.67              Good      Pass
69        S0070   16  Female      9                  5.8                     91           Graduate             Yes                        Yes          93             93             41                   76             75.67              Good      Pass
70        S0071   14  Female     10                  1.5                     50       Postgraduate              No                         No          90             81             48                   80             73.00              Good      Pass
71        S0072   14    Male     12                  3.6                     58       Postgraduate              No                        Yes          71             96             67                   49             78.00              Good      Pass
72        S0073   17  Female     11                  1.8                     76        High School              No                        Yes          60             49             83                   79             64.00           Average      Pass
73        S0074   15  Female     11                  2.9                     57       Postgraduate              No                         No          85             71             67                   78             74.33              Good      Pass
74        S0075   18    Male      9                  5.7                     84           Graduate             Yes                        Yes          56             85             75                   65             72.00              Good      Pass
75        S0076   17  Female     12                  2.2                     67       Postgraduate              No                        Yes          78             49             88                   46             71.67              Good      Pass
76        S0077   14    Male     12                  1.3                     50        High School              No                         No          47             62             65                   94             58.00           Average      Pass
77        S0078   14  Female     10                  2.1                     57        High School              No                         No          48             77             89                   45             71.33              Good      Pass

In [ ]:
df.fillna(100, inplace= True)

In [ ]:
df['Age'].fillna(25)

0       15
1       19
2       14
3       18
4       14
        ..
4995    17
4996    19
4997    16
4998    15
4999    19
Name: Age, Length: 5000, dtype: int64

In [ ]:
df_new = df.drop_duplicates()

In [ ]:
df['Previous_Year_Score'] = pd.to_datetime(df['Previous_Year_Score'], format = '%d%m%y', errors= 'ignore')

In [ ]:
avg_gender_math_score = drop_df.groupby('Gender')['Science_Score'].mean()
print(avg_gender_math_score)

Gender
Female    66.910693
Male      66.879444
Name: Science_Score, dtype: float64

In [ ]:
drop_df.aggregate(['sum','min'])

,Student_ID,Age,Gender,Class,Study_Hours_Per_Day,Attendance_Percentage,Parental_Education,Internet_Access,Extracurricular_Activities,Math_Score,Science_Score,English_Score,Previous_Year_Score,Final_Percentage,Performance_Level,Pass_Fail
sum,S0001S0002S0003S0004S0005S0006S0007S0008S0009S...,82544,MaleFemaleFemaleFemaleMaleMaleMaleFemaleFemale...,52482,16436.3,374599,PostgraduateGraduateHigh SchoolPostgraduateHig...,NoNoYesYesYesNoNoNoNoYesYesYesYesNoNoNoNoNoNoY...,NoYesYesNoNoYesNoYesNoNoNoNoYesYesYesNoYesYesN...,338774,334477,338914,336411,337388.28,AverageAverageGoodAveragePoorGoodGoodAverageAv...,PassPassPassPassFailPassPassPassPassPassPassPa...
min,S0001,14,Female,9,0.5,50,Graduate,No,No,35,35,35,40,36.33,Average,Fail

In [ ]:
new_order_file = pd.read_csv('')
merged_data = pd.merge(drop_df, new_order_file, on='Student_ID')
print(merged_data)

In [13]:
drop_df.to_json('output.json')

In [14]:
drop_df.to_parquet('output.parquet')